### ISSUE TITLE
"Error occured while reading the file buffers" on Vercel / production environment

### ISSUE THREAD

**Issue by philohelp** [harshankur/officeParser#16]
Using the buffer, it all works fine on localhost but I get an "Error occured while reading the file buffers" when I try to use in a production environment. I don't have a clue on why it does that...

**Comment by tdwoods** [comment]
I'm having this issue as well.. were you able to figure it out?

**Comment by sumedh-nimkarde-qatalog** [comment]
same here

**Comment by viktor-urbanas-qatalog** [comment]
+1

**Comment by Keaanm** [comment]
+1

**Comment by yutakusuno** [comment]
I might have come across the same issue. Here's how I managed to resolve it:

First, I encountered the same error message in my Next.js app that's hosted on Vercel. My app utilizes API route handlers for processing, which get bundled into Serverless Functions on deployment.

The problem arises because officeParser uses a directory named `officeParserTemp` for tem files by default. However, on Vercel, this directory is inaccessible, as Serverless Functions can only write to the `/tmp` directory, which is likely part of Vercel's OS system rather than the app itself. If you need more than 500 MB of space, you may need to use external file storage. You can find more information on this here: [Vercel Documentation](https://vercel.com/docs/functions/runtimes#file-system-support).

To solve this, I specified `/tmp` as the location for temp files in the configuration:

```typescript
import officeParser, { type OfficeParserConfig } from "officeparser";

const createOfficeParserConfig = (): OfficeParserConfig => {
  const config: OfficeParserConfig = {};
  if (process.env.NODE_ENV === "production") {
    config.tempFilesLocation = "/tmp";
  }
  return config;
};

const file: File = targetFile
const fileBuffer = Buffer.from(await file.arrayBuffer());
const text = await officeParser.parseOfficeAsync(
  fileBuffer,
  createOfficeParserConfig()
);
```

Ref: https://github.com/my-joshu/my-joshu/pull/26
