### ISSUE TITLE
Strange tests were introduced

### ISSUE THREAD

**Issue by c121914yu** [harshankur/officeParser#30]
![image](https://github.com/harshankur/officeParser/assets/50446880/f1f9e55e-f34f-4cd1-b88b-d2c5373be25f)

```ts
import { ReadFileByBufferParams, ReadFileResponse } from './type.d';
import { parseOfficeAsync } from 'officeparser';

export const readPptxRawText = ({ buffer, encoding }: ReadFileByBufferParams): ReadFileResponse => {
  // buffer to local file

  const result = parseOfficeAsync(buffer);
  console.log(result);
  return {
    rawText: ''
  };
};
```
I simply introduced the library, and before it was implemented, inexplicable tests would appear.Has anyone come across it?

**Comment by ChadHelbling** [comment]
seeing the same, looks like it might be from the pdf-parse dep
https://gitlab.com/autokent/pdf-parse/-/issues/24

**Comment by harshankur** [comment]
I will push a new commit that will replace pdf parsing support from pdf-parse library to Mozilla's pdf.js library which is incredibly popular. And to make things simpler because pdf.js also has ESM problems, I am committing a local build of pdf.js in the code. That should fix everything. Let me know if the bugs persist.
